### PR TITLE
Fix 'no matches found' parity

### LINKED ISSUE #72: No matching packages output difference
> Additionally the output for returning no results is very slightly different. (Honestly, doesn't really seem noteworthy but I thought I'd document the difference and leave it up to the developer.)
> 
> 
> 
> wezterm-gui_1AzxlzLxHY 

 _Originally posted by @Alfamari in [#67](https://github.com/shilangyu/scoop-search/issues/67#issuecomment-2363012559)_

It's a minute difference, but I figured I'd promote it to its own issue for documentation and PR purposes.

### PR DESCRIPTION
**Pull request by evaneliasyoung**
This resolves #72
Using `std.io.BufferedWriter` is a first step in output parity as it allows for color support detection.

### CODE REVIEW

File: src/main.zig [hunk 1]
```diff
@@ -116,40 +116,45 @@ fn printResults(allocator: std.mem.Allocator, results: *std.ArrayList(SearchResu
...
 
-    // reserve some conservative amount of memory to avoid initial allocs
-    var buffer = try std.ArrayList(u8).initCapacity(allocator, 8 * 1024);
-    defer buffer.deinit();
+    // get a buffered writer for stdout
+    const stdout = std.io.getStdOut();
+    var bw = std.io.BufferedWriter(8 * 1024, std.fs.File.Writer){ .unbuffered_writer = stdout.writer() };
+    defer stdout.close();
+
+    const colorConfig = std.io.tty.detectConfig(stdout);
```
Comment (shilangyu) [inline src/main.zig:124]: Could be created only once needed right (I think it makes a syscall on windows)?

**Review by shilangyu — APPROVED** [review]

**Comment by shilangyu** [comment]
Sorry for the delay, I had an exam session

**Comment by shilangyu** [comment]
Do you plan to address the comment? If not I can try to take over this PR

**Comment by evaneliasyoung** [comment]
Sorry for the delay, yes, I can take care of it.

**Review by shilangyu — APPROVED** [review]
Thank you!
